### ISSUE TITLE
Validate standard deviation calculation is applicable

### ISSUE THREAD

**Issue by nishihatapalmer** [ostafen/smart#12]
We use the method to calculate standard deviation that assumes a normal distribution.

Should we instead calculate a probability table for search times and compute standard deviation over the probabilities?

**Comment by nishihatapalmer** [comment]
https://www.statology.org/standard-deviation-of-probability-distribution/

It's not clear to me whether this is necessary or appropriate - I'm not a stats expert.  I'm not convinced search times follow a normal distribution though.

**Comment by ostafen** [comment]
I think we should run a statistical hypothesis test to assess if search times distribute according to a gaussian, and then proceed consequently

**Comment by nishihatapalmer** [comment]
The data is clearly skewed somewhat to the right for most algorithms.  

I constructed a frequency histogram of search times for EPSM and HC.  Both showed a skew to the right.  EPSM was quite tightly clustered, but with a bit more to the right.  HC also had two peaks with a dip between them, before tailing off to the right.

Evidence from having the median stat also supports this conclusion.  In general, the median value is smaller than the mean value for all algorithms profiled so far.

So we have some skew - and even double peaks in the search time frequency.  I am not qualified to say whether this means our standard deviation calculation is OK or not though.

What evidence would we need to put in front of someone who actually understands statistics well enough?

**Comment by nishihatapalmer** [comment]
I have found some information on measurement of variation in software bench-marking here, which is directly applicable to our benchmarking here: https://stats.stackexchange.com/questions/1895/determining-the-variability-of-a-benchmark

It mentions that the absolute deviation is more robust than the standard deviation: https://en.wikipedia.org/wiki/Absolute_deviation

There is a useful paper on statistically rigorous benchmarking of Java programs here: https://dri.es/files/oopsla07-georges.pdf

While the Java-specific parts are not applicable, the evaluation of statistics in benchmarking is.

**Comment by nishihatapalmer** [comment]
One conclusion of the paper seems to be that confidence intervals are extremely useful.  They recommend them to summarize results of k runs over q different processes (e.g. forked).

Classifies results by how confidence intervals overlap.

![image](https://user-images.githubusercontent.com/4427300/207039316-4cf4572d-de20-4668-a30c-8f0ca2788260.png)

**Comment by nishihatapalmer** [comment]
Also useful: https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance

**Comment by nishihatapalmer** [comment]
Ordered the book "Measuring Computer Performance - A Practitioner's Guide", by
David J. Lilja from Cambridge University Press.

Has sections on benchmarking statistics, software, variation, errors.  Looks useful.

**Comment by nishihatapalmer** [comment]
One observation is that we calculate a population standard deviation, not a sample standard deviation:

```C
double compute_std(double avg, double *T, int n)
{
    double std = 0.0;
    for (int i = 0; i < n; i++)
        std += pow(avg - T[i], 2.0);

    return sqrt(std / n);
}
```

However, we are taking a sample from the population of all possible searches of a given length, so I think we should use the sample standard deviation calculation, which divides by (n - 1) instead of n.  

See https://www.statology.org/population-vs-sample-standard-deviation/ for one explanation, there are lots of others.

My understanding is that using n underestimates the variance in a population, because the population as a whole will almost certainly contain more  variance than in the sample you examined.  Therefore, n - 1 is regarded as a better value to choose for sample standard deviations.  This  introduces a bias in the other direction, which tends to give better estimates.

**Comment by nishihatapalmer** [comment]
I have submitted a PR that uses the sample standard deviation rather then the population standard deviation.   I am confident this is the right measure when sampling from a population (randomized tests of all possible patterns and texts to search).

**Comment by nishihatapalmer** [comment]
### Keep it with caveats

The standard deviation can be misleading, as search result times are not sampled randomly from a Gaussian distribution.  Variation in search results arises from different patterns performing better or worse, and they do not give a nice bell curve.   Results are usually skewed a bit to the right, with a long tail of slower results, but most results clustered towards the faster end.  Sometimes there is more than one peak of timings. 

In any case, the standard deviation is still a useful piece of information, but it has to be taken in context with other statistics and with an understanding that it is not giving as complete a picture as it would if the results were genuinely sampled from a Gaussian.

It tells you roughly how much variation you are getting on average.
