### ISSUE TITLE
Provide an option in select to allow the set of algorithms to be emptied

### ISSUE THREAD

**Issue by simonefaro** [ostafen/smart#26]
It would be convenient to have an option to remove all selected algorithms.
The original version of smart had the -none option that lost to do this with a single command

**Comment by nishihatapalmer** [comment]
The --none option (or -n) option exists in the current code.  It's not printed in the help though.

**Comment by nishihatapalmer** [comment]
`smart select --none`

**Comment by nishihatapalmer** [comment]
Fixed  by #30
